# Generated by Django 4.1.2 on 2023-05-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tfc", "0002_monitorizacao_plantacuidada_tratamento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planta",
            name="expo_solar",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="planta",
            name="quantidade_agua",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="planta",
            name="quantidade_fertilizante",
            field=models.FloatField(default=0.0),
        ),
    ]
