# Generated by Django 4.1.2 on 2023-05-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tfc", "0003_alter_planta_expo_solar_alter_planta_quantidade_agua_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planta", name="descricao", field=models.TextField(default=""),
        ),
    ]
