# Generated by Django 4.1.2 on 2023-05-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tfc", "0004_alter_planta_descricao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planta",
            name="expo_solar",
            field=models.CharField(max_length=32),
        ),
    ]
