# Generated by Django 4.1.2 on 2023-06-22 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tfc", "0006_remove_utilizador_genero_notificacao"),
    ]

    operations = [
        migrations.RemoveField(model_name="planta", name="expo_solar",),
        migrations.RemoveField(model_name="utilizador", name="idade",),
    ]
